### ISSUE TITLE
Vriendenoverzicht

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/PopcornFriends#11]
volgende functies mogen toegevoegd worden

- [x] toevoegen van vrienden
- [ ] verwijderen
- [ ] blokkeren

**Comment by mickverm** [comment]
![friends](https://cloud.githubusercontent.com/assets/1834265/19223499/c1233cc4-8e71-11e6-864f-45174bee1f12.png)

**Comment by mickverm** [comment]
![addfriends](https://cloud.githubusercontent.com/assets/1834265/19223561/067bbd9a-8e73-11e6-873c-f50bf236fecd.png)

**Comment by mickverm** [comment]
Vriendenoverzicht:

- Overzicht van al je vrienden
- zoeken tussen je vrienden
- knop om vrienden toe te voegen

Vrienden toevoegen

- Zoeken op basis van naam
- already on watchfriends -> vrienden van vrienden etc.
