### ISSUE TITLE
Kalender pagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/PopcornFriends#12]
Wat doen we hier?

- [ ] planing aankomende uitzendingen op TV
- [ ] persoonlijke planning

**Comment by ExCellRaD** [comment]
persoonlijke planning?

**Comment by HeinPauwelyn** [comment]
Was inderdaad niet idee van de planning maar is mss een nice to have. kunnen dat er nog altijd uit laten.

**Comment by ExCellRaD** [comment]
Mss wel, maar ik heb het gevoel dat we al genoeg paginas gaan hebben.

**Comment by HeinPauwelyn** [comment]
dat is waar. ga ik on hold plaatsen en issue sluiten
