### ISSUE TITLE
Overzicht gevolgde seriespagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/PopcornFriends#15]
Zegt het zelf

**Comment by HeinPauwelyn** [comment]
Vind wel dat er meer mag inkomen dan alleen gevolgde series. ook de series die je graag wilt volgen mogen er ook bij maar dan onder een andere tab of zo.

**Comment by mickverm** [comment]
![overzicht gevolgde series](https://cloud.githubusercontent.com/assets/1834265/19223689/23e90da8-8e76-11e6-840a-fcba7f09ce4f.png)

**Comment by HeinPauwelyn** [comment]
#34
