### ISSUE TITLE
Beschrijving van de applicatie

### ISSUE THREAD

**Issue by nielsbril** [HeinPauwelyn/PopcornFriends#17]
Doel, functionaliteit & features, vermarkting uitleggen in document.

**Comment by HeinPauwelyn** [comment]
Is dat niet iets voor op de wiki?

**Comment by nielsbril** [comment]
Ik bedoel in het document voor Walcarius.

**Comment by HeinPauwelyn** [comment]
Dat was dan neit zo duidelijk omschreven.
