### ISSUE TITLE
Lijsten

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/PopcornFriends#4]
**Watchlist**

1. Future
2. Now
3. Past

_Opmerking:_ Een film mag slechts in één lijst staan per gebruiker!

**Andere:**

1. Favorieten
2. **Optioneel:** Collecties

**Comment by ExCellRaD** [comment]
![android_phone_lijst](https://cloud.githubusercontent.com/assets/12865871/19213771/cf2a2eac-8d74-11e6-97d3-d5cceb793dfe.png)
![iphone_lijst](https://cloud.githubusercontent.com/assets/12865871/19213773/d29836b0-8d74-11e6-8c29-a892cf284435.png)
![windows_phone_lijst](https://cloud.githubusercontent.com/assets/12865871/19213774/d47a4f0e-8d74-11e6-902e-9b2dfd5dde93.png)

**Comment by ExCellRaD** [comment]
In android zitten alle apparte lijsten in de sidebar van het hoofdmenu, bij windows en iOs zijn het tabbladen. Dus op android kan je dit scherm enkel bereiken via het hoofdmenu. 
Klikken op een serie -> details pagina
Searchknop -> zelfde als op home
backbutton -> home
switchen tussen lijsten kan via sidebar opendoen -> andere selecteren / of via de tabbladen op de andere platforms.
