### ISSUE TITLE
Startpagina

### ISSUE THREAD

**Issue by HeinPauwelyn** [HeinPauwelyn/PopcornFriends#9]
Wat doen we op deze pagina?

**Comment by HeinPauwelyn** [comment]
# Smartphone

## Android

![home phone android](https://cloud.githubusercontent.com/assets/16222780/19212231/823df01e-8d4d-11e6-92dc-2f8c19c691b2.png)

## iOS

![home phone ios](https://cloud.githubusercontent.com/assets/16222780/19212232/8254480a-8d4d-11e6-89b7-f27bffcc82e0.png)

## Windows 10

![home phone windows](https://cloud.githubusercontent.com/assets/16222780/19212234/8266a810-8d4d-11e6-8fb1-9c03844494de.png)

# Tablet

## Android

![home tablet android](https://cloud.githubusercontent.com/assets/16222780/19212235/82672b96-8d4d-11e6-87c9-50083522194c.png)

## iOS

![home tablet ios](https://cloud.githubusercontent.com/assets/16222780/19212236/8267c0c4-8d4d-11e6-88a2-590405f06724.png)

## Windows 10

![home tablet windows](https://cloud.githubusercontent.com/assets/16222780/19212233/8265b7ca-8d4d-11e6-8134-1ae40b694803.png)

# Opmerking

* Heb alles gemaakt met [Balsamiq][1].

 [1]: https://webdemo.balsamiq.com/

**Comment by ExCellRaD** [comment]
Iets wat er nog bij kan is profiel informatie van de user zelf.

**Comment by HeinPauwelyn** [comment]
gaat het over het hamburgermenu op windows 10?

**Comment by ExCellRaD** [comment]
Maar we maken geen app om films te kijken he, we willen vooral die achievements en vrienden koppelen aan een seriestracker. Er is trouwens niet echt veel plaats nodig, gewoon username en een lijstje van achievement icoontjes. Het zou echt niet handig zijn om dat in de settings te plaatsen.

**Comment by HeinPauwelyn** [comment]
profiel pagina van de gebruiker dan?

**Comment by HeinPauwelyn** [comment]
ga ze nog wat aanpassen

**Comment by HeinPauwelyn** [comment]
Aangepast:

[![image](https://cloud.githubusercontent.com/assets/16222780/19677585/4322b4fa-9a9a-11e6-8391-4c1f887aeefb.png)](https://cloud.githubusercontent.com/assets/16222780/19677585/4322b4fa-9a9a-11e6-8391-4c1f887aeefb.png)

zie ook #47 over dat zijdelings scrollen
